import Foundation
import SwiftData

/// Versioned from V1 (roadmap §7f.1) so the native app never repeats the web
/// app's unversioned schema drift — even though V1 has no migration stage yet.
///
/// ⚠️ V1's SHIPPED SHAPE IS PERMANENT (frozen 2026-08-13, beta P0). The live
/// model classes have since grown into V2 below, so this list resolves to the
/// current shape; what is pinned — by `SchemaFreezeTests` — is that every
/// model and property V1 shipped STILL EXISTS. Nothing here may ever be
/// removed or renamed: a CloudKit-backed store only supports additive
/// lightweight migration, and existing libraries must keep opening.
enum LevelSelectSchemaV1: VersionedSchema {
    static var versionIdentifier: Schema.Version { Schema.Version(1, 0, 0) }

    static var models: [any PersistentModel.Type] {
        [
            Profile.self,
            Game.self,
            Playthrough.self,
            Session.self,
            CompletionEvent.self,
            TrackerSchemaRecord.self,
            TrackerStateRecord.self,
            Run.self,
            GameMap.self,
            Marker.self,
            MigrationReceipt.self,
            ThemeSettings.self,
            GameVideo.self,
            GameCollection.self,
        ]
    }
}

/// V2 (2026-08-19) — purely ADDITIVE over V1: new optional fields, two new
/// models, nothing renamed, nothing removed. That constraint isn't stylistic;
/// CloudKit only supports lightweight-migratable changes, so removals and
/// renames are permanently off the table for this store.
///
/// Landed as ONE batch, deliberately, in the window between build 24 going up
/// and the first tester installing: every field CloudKit has never seen must
/// be promoted Development→Production before any build writes it (see
/// `CloudKitSchemaSeeder`), and doing that once for eight items beats doing it
/// eight times. Several fields therefore ship AHEAD of the features that use
/// them — an unused optional costs nothing, and a Schema V3 costs a great deal.
enum LevelSelectSchemaV2: VersionedSchema {
    static var versionIdentifier: Schema.Version { Schema.Version(2, 0, 0) }

    static var models: [any PersistentModel.Type] {
        LevelSelectSchemaV1.models + [
            TrackerItemDetail.self,
            EarnedBadge.self,
        ]
    }
}

/// V3 (2026-08-28) — the first user-generated BYTES in the store.
///
/// Additive like V2, and for the same unbreakable reason. One new model
/// (`GameImage`) plus artwork-role pointers on `Game` and a backdrop
/// intensity on `ThemeSettings`.
///
/// `GameImage.data` is `.externalStorage`, so the bytes live beside the store
/// rather than in a row, and CloudKit mirrors them as a CKAsset. That is the
/// only reason a photo library is affordable to sync at all — and the reason
/// ingest downscales before writing (`ImageIngest`): what the store keeps is
/// what every device downloads.
enum LevelSelectSchemaV3: VersionedSchema {
    static var versionIdentifier: Schema.Version { Schema.Version(3, 0, 0) }

    static var models: [any PersistentModel.Type] {
        LevelSelectSchemaV2.models + [
            GameImage.self,
        ]
    }
}

/// Deliberately NO `SchemaMigrationPlan`.
///
/// A staged plan crashed every existing library on first launch:
/// `NSCocoaErrorDomain 134504 — "Cannot use staged migration with an unknown
/// model version."` Staged migration identifies the on-disk store by matching
/// it to one of the declared versions. `LevelSelectSchemaV1` resolves to the
/// LIVE model classes, which have since grown into V2, so nothing declared
/// matched what was actually on disk and the store refused to open — taking
/// the app down at launch, because a library that cannot open is fatal.
///
/// Making staged migration work would mean snapshotting all 14 V1 models as
/// frozen copies (~1,000 lines whose only job is never to change). It buys
/// nothing here: every change this store can ever make is additive, since
/// CloudKit supports nothing else, and Core Data infers additive mappings on
/// its own. `NSMigratePersistentStoresAutomaticallyOption` and
/// `NSInferMappingModelAutomaticallyOption` are already set on the store, so
/// opening with the current schema migrates an older one in place.
///
/// The versioned schemas above stay as the written record of the shape at each
/// version, and `SchemaFreezeTests` asserts against them. If a change ever
/// genuinely needs transforming data, do it as an idempotent pass in app code
/// — not a custom stage on a CloudKit-backed store.
enum LevelSelectMigrationPlan {
    static var schemas: [any VersionedSchema.Type] {
        [LevelSelectSchemaV1.self, LevelSelectSchemaV2.self, LevelSelectSchemaV3.self]
    }
}

/// Shared container builder.
/// - App: SwiftData + CloudKit (`.automatic`) → automatic iCloud sync, no auth.
/// - Tests/previews: in-memory, non-CloudKit, so they run headless without iCloud.
enum LevelSelectStore {
    /// The container everything in the app process uses — app UI, notification
    /// actions, Live Activity intents.
    ///
    /// Computed rather than stored because the demo library swaps it wholesale
    /// (see `LibrarySwitcher`). Call sites don't need to care which library is
    /// open; they just want the current one.
    @MainActor
    static var shared: ModelContainer { LibrarySwitcher.shared.container }

    /// True when the container fell back to a LOCAL (non-CloudKit) store
    /// because CloudKit failed to initialize. The sync status UI surfaces
    /// this — the fallback itself must never be silent again (beta P0).
    @MainActor
    static private(set) var usingLocalFallback = false

    /// Where the demo library lives — a *separate file* from the real one.
    ///
    /// The point of a second store rather than a hidden-flag on each record:
    /// the real library isn't filtered or marked, it simply isn't open, so no
    /// filtering bug can show or delete the wrong rows. And demo records never
    /// exist in the CloudKit store at all, so they can't sync to other devices
    /// or need purging afterwards.
    @MainActor
    static var demoStoreURL: URL {
        URL.applicationSupportDirectory.appending(path: "demo.store")
    }

    @MainActor
    static func makeContainer(inMemory: Bool = false, demo: Bool = false) -> ModelContainer {
        let schema = Schema(versionedSchema: LevelSelectSchemaV3.self)
        // Never use CloudKit under XCTest (the app is the test host) or in-memory.
        let underTest = ProcessInfo.processInfo.environment["XCTestConfigurationFilePath"] != nil
        let memory = inMemory || underTest

        if memory {
            let config = ModelConfiguration(schema: schema, isStoredInMemoryOnly: true)
            return try! ModelContainer(for: schema, configurations: [config])
        }

        if demo {
            // Application Support isn't guaranteed to exist on iOS until
            // something creates it, and a store URL inside a missing directory
            // just fails — which would silently drop the demo library to the
            // in-memory fallback below and lose it on every relaunch.
            try? FileManager.default.createDirectory(
                at: URL.applicationSupportDirectory, withIntermediateDirectories: true)

            // Deliberately CloudKit-free. Screenshot fodder has no business in
            // anyone's iCloud, and keeping it local means switching back leaves
            // nothing behind to clean up.
            let config = ModelConfiguration(schema: schema, url: demoStoreURL,
                                            cloudKitDatabase: .none)
            if let container = try? ModelContainer(for: schema, configurations: [config]) {
                return container
            }
            // Falling back to the real library would be the one genuinely
            // dangerous outcome here — seeding demo data into it is exactly
            // what this feature exists to prevent. In-memory instead: the demo
            // is disposable by nature.
            let memoryOnly = ModelConfiguration(schema: schema, isStoredInMemoryOnly: true)
            return try! ModelContainer(for: schema, configurations: [memoryOnly])
        }

        // App: SwiftData + CloudKit (`.automatic`) → automatic iCloud sync, no auth.
        do {
            let config = ModelConfiguration(schema: schema, cloudKitDatabase: .automatic)
            return try ModelContainer(for: schema, configurations: [config])
        } catch {
            // Resilience: if CloudKit is unavailable, keep working from a local store.
            let local = ModelConfiguration(schema: schema)
            if let container = try? ModelContainer(for: schema, configurations: [local]) {
                usingLocalFallback = true
                return container
            }
            fatalError("Failed to create ModelContainer: \(error)")
        }
    }
}
